### PR TITLE
add basic docker build system

### PR DESCRIPTION
**Pull request by mandric**
I could not get `make -j` to work for some reason with docker.  Will google it tomorrow but thought I would submit this for any feedback to check if it's moving in the right direction.

### CODE REVIEW

**Comment by mandric** [comment]
If you like this, was thinking to add it to a GitHub workflow so you can automatically build on commit/PRs.

**Comment by mandric** [comment]
Actually the latest commit (82a9b7f8bd7d37f364a67a30064410a3d74b386f) gives me an error now when I build:

```
../../programs/clariond/src/index.ts(3,29): error TS2307: Cannot find module 'clwasmer' or its corresponding type declarations.
make[2]: *** [ts/CMakeFiles/dist.dir/build.make:63: ts/CMakeFiles/dist] Error 2
make[1]: *** [CMakeFiles/Makefile2:152: ts/CMakeFiles/dist.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by davidsilvasmith** [comment]
Would love a docker build system so build will always work.

**Comment by tbfleming** [comment]
`make -j` worked on my machine. It may have caused it to use more memory than you have available; look for a "killed" message.

I made some minor tweaks and merged it. Thanks for the contribution!

**Comment by mandric** [comment]
Do you want a GitHub workflow setup? So for example on commit or PR Github would build and test using the docker setup.

**Comment by tbfleming** [comment]
Eventually. At this stage the main branch is frequently broken and we have multiple people committing directly to it. After the code starts to solidify, CI will become more important.

**Pull request merged**
